[package]
name = "terminal_hud"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
toml = "0.7.1"
ureq = { version = "*", features = ["json"] }
